apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # This pulls the exact version you requested from the source
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0/deploy/static/provider/cloud/deploy.yaml

# You can add common labels to all ingress-nginx resources here
labels:
- includeSelectors: true
  pairs:
    managed-by: gitops-team
    app.kubernetes.io/part-of: ingress-external