apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: my-boutique
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:latest
          ports:
            - containerPort: 9411
          env:
            # For a dev environment, we store spans in memory. 
            # In prod, you would link this to your Elasticsearch.
            - name: STORAGE_TYPE
              value: "mem" 
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"