apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: my-boutique
spec:
  selector:
    app: order-service # Must match the label in the Deployment template
  ports:
    - protocol: TCP
      port: 80          # The port other services use
      targetPort: 8080  # The port at which the Spring Boot app is listening on
  type: ClusterIP       # Use ClusterIP for internal-only microservices