spring:
  application:
    name: MyBoutique
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha # Sorts endpoints alphabetically
    tags-sorter: alpha
  show-actuator: true # Optional: shows health check endpoints in Swagger