spring:
    application:
        name: customer-service
        
  # datasource:
  #   url: jdbc:postgresql://postgres-customer-service-headless:5432/${POSTGRES_DB_NAME}
  #   username: ${SPRING_DATASOURCE_USERNAME}
  #   password: ${SPRING_DATASOURCE_PASSWORD}  
