apiVersion: v1
kind: ConfigMap
metadata:
  name: swagger-ui-config
  namespace: my-boutique
data:
  urls.json: |
    [
      {
          "url": "/v3/api-docs/product-service",
          "name": "Product Service"
      },
      {
          "url": "/v3/api-docs/order-service",
          "name": "Order Service"
      },
      {
          "url": "/v3/api-docs/customer-service",
          "name": "Customer Service"
      }
    ]