spring:
  application:
    name: product-service

  # datasource:
  #   url: jdbc:postgresql://postgres-product-service-headless:5432/${POSTGRES_DB_NAME}
  #   username: ${SPRING_DATASOURCE_USERNAME}
  #   password: ${SPRING_DATASOURCE_PASSWORD}    