server:
  port: 9990

resilience4j:
  circuitbreaker:
    configs:
      # This creates a local 'template' for product-service
      product-service-defaults:
        baseConfig: global-shared-config # Inherit from the global application.yml
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10
    
    instances:
      review-service-resilience:
        baseConfig: product-service-defaults # Inherit from the local template
        failureRateThreshold: 30
        
      product-service-resilience:
        baseConfig: product-service-defaults
        failureRateThreshold: 50
        
      category-service-resilience:
        baseConfig: product-service-defaults
        failureRateThreshold: 60